[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "logistic_regression-lib"
version = "0.1.0"
description = "A simple logistic regression model implemented from scratch."
authors = [{ name = "Gauri" }]
dependencies = ["numpy"]
