[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "regression-lib"
version = "0.1.0"
description = "A simple regression model containing linear and logistic classes implemented from scratch."
authors = [{ name = "Gauri" }]
dependencies = ["numpy"]
